services:
  db:
    image: postgres
    container_name: postgres_crpizza
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crpizza

volumes:
  postgres_data:
